compressionLevel: mixed

defaultSemverRangePrefix: ""

enableConstraintsChecks: true

enableGlobalCache: false

enableProgressBars: false

enableTelemetry: false

httpRetry: 5

logFilters:
  - level: warning

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.1.1.cjs
